#!/bin/sh

# # #
# Brian Hession, James Miller, Erik Wenkel
#
# Main entry point to classcatcher with gtk
#
#

DIR='ABSDIR'

### Take argument
arg=$1

### Help screen
if [ ! -z $arg ]; then
	if [ $arg = '-h' ] || [ $arg = '--help' ]; then
		echo "Usage: classcatcher-client [options]\n"
		echo "Options"
		echo "-h, --help\tShow this help screen"
		echo "-s, --show\tShows the gtk client"
		exit 0
	fi

	### Show gtk
	if [ $arg = '-s' ] || [ $arg = '--show' ]; then
		$DIR/classcatcher-gtk
		if ps -C run > /dev/null
		then
			killall run
		fi
		$DIR/include/run
		exit 0
	fi
fi

### Main entry
### Check if process is running
if ps -C run > /dev/null
then
	$DIR/classcatcher-gtk
	killall run
fi
$DIR/include/run

