#!/bin/sh

# # #
# Brian Hession, James Miller, Erik Wenkel
#
# Main entry point to classcatcher with gtk
#
#

DIR='ABSDIR'

### Check if process is running
if ps -C run > /dev/null
then
	$DIR/classcatcher-gtk
	killall run
fi
$DIR/include/run

