#!/bin/bash

# # #
# Brian Hession, James Miller, Erik Wenkel
#
# Main entry point for classcatcher gtk
#
#

DIR='ABSDIR'

### Get file names
credfile=$DIR'/etc/.cred'
configfile=$DIR'/etc/.config'
coursesfile=$DIR'/etc/.courses'

### Read Credential file
if [ -f $credfile ]; then
	exec 3<&0
	exec <$credfile

	pos=0
	while read line
	do
		cred[pos]=$line
		pos=`expr $pos + 1`
	done
	
	exec <&3
else
	$DIR/classcatcher-gtk
fi

### Read Configuration file
if [ -f $configfile ]; then
	exec 3<&0
	exec <$configfile
	
	pos=0
	while read line
	do
		config[pos]=$line
		pos=`expr $pos + 1`
	done
	
	exec <&3
else
	$DIR/classcatcher-gtk
fi

### Read Courses file
if [ ! -f $coursesfile ]; then
	$DIR/classcatcher-gtk
fi

### Check if process is running
if ps -C classcatcher > /dev/null
then
	killall classcatcher
fi
if ps -C conky > /dev/null
then
	killall conky
fi

### Run classcatcher python script
touch $DIR/etc/classcatcher.log
conky -c $DIR/etc/.conkyrc_classcatcher &
$DIR/classcatcher -q -l "${cred[0]}" "${cred[1]}" -d ${config[0]} -f $coursesfile

